### ISSUE TITLE
"to" field is empty

### ISSUE THREAD

**Issue by skorokithakis** [alash3al/smtp2http#10]
Here's the SMTP exchange:

```
220 smtp2http ESMTP Service Ready
HELO zeus
250 2.0.0 Hello zeus
MAIL FROM:<stavros@zeus>
250 2.0.0 Roger, accepting mail from <stavros@zeus>
RCPT TO:<youremail@example.com>
250 2.0.0 I'll make sure <youremail@example.com> gets this
DATA
354 2.0.0 Go ahead. End your data with <CR><LF>.<CR><LF>
Received: (nullmailer pid 142148 invoked by uid 1000);
	Wed, 10 Jun 2020 10:01:02 -0000
Date: Wed, 10 Jun 2020 13:01:02 +0300
Message-Id: <1591783262.002746.142147.nullmailer@zeus>
From: stavros <stavros@zeus>
Cc: recipient list not shown: ;

.
250 2.0.0 OK: queued
QUIT
221 2.0.0 Goodnight and good luck
```

And here's the received body:

```
{"spf":"temperror","id":"1591783262.002746.142147.nullmailer@zeus","date":"2020-06-10 13:01:02 +0300 EEST","resent_date":"0001-01-01 00:00:00 +0000 UTC","body":{},"addresses":{"from":{"name":"stavros","address":"stavros@zeus"},"to":[]}}
```

You can see that youremail@example.com is not shown anywhere, and it should be.

**Comment by alash3al** [comment]
I'm unable to reproduce the issue, could you send me the whole command you generated this email through? as I tried to send manually "via a code" and it succeeded.

**Comment by skorokithakis** [comment]
I installed nullmailer and added this line to /etc/nullmailer/remotes:

```
localhost smtp
```

Then used sendmail to send the email. Does pasting my session in not reproduce the problem?

**Comment by alash3al** [comment]
I tried the mentioned session messages, and I didn't catch it

**Comment by skorokithakis** [comment]
Hmm, that's odd, you tried directly by telnet?

**Comment by alash3al** [comment]
I'm trying it now ..

**Comment by alash3al** [comment]
Caught it "using pure telnet", it is wired but I'm investigating

**Comment by skorokithakis** [comment]
I suspect you're getting the email address from a header in the email, rather than the MAIL TO command.

**Comment by alash3al** [comment]
Yup, that is what I found, anyway, it is being released now

**Comment by skorokithakis** [comment]
Thanks!

**Comment by alash3al** [comment]
It is released, go [there](https://github.com/alash3al/smtp2http/releases/tag/v3.1.0)
