### ISSUE TITLE
Where to enter password for smtp?

### ISSUE THREAD

**Issue by alloc33** [alash3al/smtp2http#13]

**Comment by alash3al** [comment]
The main purpose for `smtp2http` is to redirect the `SMTP` traffic directly to `HTTP` endpoint which should do its own logic, so it has no authentication mechanism

**Comment by alash3al** [comment]
Could you tell me your use case?

**Comment by tsuijten** [comment]
I would like the same thing. Main reason for a username and password is that I need to host the SMTP server "openly" on the web. I don't want other people to be able to send emails to this SMTP server. Being able to set a username / password prevents this.

Would it be possible for you to add this functionality?

**Comment by Manouchehri** [comment]
@alash3al Any reason auth was removed in b17d10ed8a04edc621c3e5612e96ccd676ad97b8?
