### ISSUE TITLE
501 MAIL command contained invalid address (in reply to MAIL FROM command)

### ISSUE THREAD

**Issue by MinasWang** [alash3al/smtp2http#5]
Hello , 

 First of all, thanks you all for the contributions. 

  I have a business scenario, which to received all customer's email request and store it in backend to further processing. I find this repository is exactly matched. So I kickoff with a cloud server and install your binary with command: 
    ./smtp2http-linux-amd64 --listen=:25 --webhook=http://<mydomain>/api/key/smtp2http --name=<myhost>.cn --strict=false

  Then I open my hotmail/ foxmail, start to send a email to this server, not sure what the receiver address should be, I just put it a randon adress like admin@myhost.cn,( of cause, I have register the domain), then I got error message like 
**host  myhost  [.9.204] said: 501 MAIL command contained invalid address (in reply to MAIL FROM command)**
  As I check port 25, it is accessible from my laptop. 

  Is there any other configuration need to be done ?

**Comment by alash3al** [comment]
Did you add an MX record that points to your email server?
