### ISSUE TITLE
Issue getting the utility

### ISSUE THREAD

**Issue by roshanjonah** [alash3al/smtp2http#6]
root@chat-srv1:/home/chat# go get github.com/uflare/smtp2http

```
# github.com/uflare/smtp2http
/root/work/src/github.com/uflare/smtp2http/handler.go:25:33: cannot use req.Message (type *mail.Message) as type io.Reader in argument to parsemail.Parse:
	*mail.Message does not implement io.Reader (missing Read method)
/root/work/src/github.com/uflare/smtp2http/handler.go:30:8: undefined: resty.R
```

**Comment by skorokithakis** [comment]
You can get the `resty` dependency by changing the import, but I don't know how to fix the first one.

**Comment by skorokithakis** [comment]
I managed to fix this on my fork: https://github.com/skorokithakis/smtp2http

**Comment by roshanjonah** [comment]
Awesome! Thank you :)

**Comment by alash3al** [comment]
@skorokithakis @roshanjonah 

sorry guys for the late reply, I did update the deps and fixed the mentioned issues

**Comment by skorokithakis** [comment]
Fantastic, thank you! Would it be possible for you to add an HTTP parameter for the rest of the headers? Eg I sometimes need In-Reply-To, and a single JSON object holding everything else suits me fine.

**Comment by alash3al** [comment]
@skorokithakis No problem, I pushed an update with all possible headers I can fetch,

I'm thinking of making a SaaS version of this software with a dashboard featuring the following:
- simply create webhooks with a click!
- ability to view logs of all webhook requests
- ability to help the developer to create webhooks via an API

...

what is your opinion, will it be good or not, I just want to remove any setup & management related hassle?

**Comment by skorokithakis** [comment]
Personally, I migrated from MailGun (which does the same) to this utility because of how simple and easy it was to set up, and because MailGun made it really hard for me to contain the cost. It was also pretty expensive for such a simple operation.

Depending on how much you charged, I might use it. I currently use it to run https://spa.mnesty.com/, and it's really good for that purpose. I have a few features I'd like to see, but since this is a side project I run in my spare time for free, I couldn't really pay anything more than a few dollars a month, and even that's a stretch, since the functionality is so simple.

**Comment by alash3al** [comment]
Great, 

Can I know how much mailgun charge for a service like this?

**Comment by skorokithakis** [comment]
They charge per incoming email, which was crazy, because it meant that a spammer can just send me a million emails and I'd have to pay tens of thousands of dollars. I'm not sure exactly how much, you can find the pricing on their site.

**Comment by alash3al** [comment]
hmmmm, what do you think about a better pricing model from your point of view? and if there were some features like spam-fighting, could it be ok?

**Comment by skorokithakis** [comment]
The problem with Mailgun is that they charge the same for incoming vs outgoing emails, when outgoing emails are a much more valuable service than incoming. If there were spam fighting, I wouldn't want this, since I explicitly only want the spam :)

**Comment by alash3al** [comment]
I understood, so the main problem is "inbound emails are same pricing as outgoing" and you're expecting that it should be about +60% less than the outbound right?

**Comment by skorokithakis** [comment]
In price? I'd expect to have a fixed-price tier, so from 1 to X emails, it's $10, then it's $30, and so on.

**Comment by alash3al** [comment]
how about something like this:  20k or 30k email = 10$?
Sorry if I'm asking a lot

**Comment by skorokithakis** [comment]
Nah no problem. I think I'm unlikely to switch right now because running the utility works fine for me. I would like something like stripping of HTML to plain text, but I implemented it myself, so my needs are currently met. That sounds like fair pricing, though.

**Comment by alash3al** [comment]
Thank you for that great discussion, if I launched the service, I would send you a coupon code with a great discount for months

**Comment by skorokithakis** [comment]
That'd be great, thanks!
